apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skooner-sa-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: skooner-sa
  namespace: kube-system
