apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  releaseName: echo-server
  chart:
    spec:
      chart: echo-server
      sourceRef:
        kind: HelmRepository
        name: eleann
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
