apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAt85WQ0jyo7FximxD+pfhc57gv4vwrA76Qb2Z3n7dsXDNjZL5sAAM4W/w1a4MYf1BDRYY8FuuhBrXO4rKooisbZYlBD43+KuC7JloxxxskrAzVcqTNMuSRDJWMz1fln9/ZYChPD//nElV+BrUqhCIE+H5XRlvlOVyS9TRLXzZneAMQNBUVbILvlm/88A50L7REkkm2QDUXRpXfeWOusCCPF1B5/piC8RgaeXGmMfZsKuZKjs1y9ekmC0sMKvXKC1lwtXPKfnhbaVl4VEak82Oo1RgIYYB1Bd3YuU9Pdx314xI1ohwtMsqO5c4aKHMsZ6kLmZxJbSxc1oURcIhAh7moIkHjlDAeOBCCpVfgsaGD91kvUAAOb68c1oljSJ2ejV9kkgyf6U6ZCXJGLAduePfKUk+VLaWCNq9pyiIuk1IbmwK0V81hd919oOKtcH+LYv/P3lge7hKGFBAAdN8NatdQ6K26vu7Ph+K6qKyZNND5Jj2XQpo9Qw38bR3S4Q9yeW+kp+OeJ1VnThZwR/2IZ7gcIfxLtJBrO8RjF+7nrpBnvKgfu+22bn6I675hreRtHFteG5VxXT7e+4FDWipnJz8BSq+utmxtYmLlmMzG5R+MIUvo7KIOwIf7ps3PoCRFe3EmYQTECPCKTuawzVDGLT+2nOKONDCt3+JASRNGotQjzEJTRNW9mVjhJ8aDWb3Zktrvcz3Y/1xmFBONq7OzVu69Y0y+//zua/dw88QVmMWF2I0GkSjFR3Nl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-token
      namespace: flux-system

