apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCp5m2X7b6fLVMcQ8VvO03FGW1L61KBqWz5jTxvSSo1bqh4KCC8endk7wbAiKxPR2h2eAkEP0c7bzNKu7M5kdwYM6p37AEqNu7MeolCOZvrUhOEyy3VjmulDWhbG/2BCH0koDvZZqocJyuh8fS8GnKb7bRtgdxV+vqSfnKlyjkFBRaATbVYX5bfRM6OqGw8YYpLJvc9yNiffnoAFtdjZAEk4XaXxH+9jKm+vAlKbBSlnDy87hKkSi78uAGW/9Z413xPW8zgD7ax23Ixxw5KLK4wnTURRJAamGAaa0mypkGf7UO+nO+I7Ejb4RWhlbpvgVe8Ya80ujxBL8YZTcl0b9oHUDaExtLFZFJvYYQDNZa5fWCIeM6/6+NjqK4cFaLHrvG0ndv/UlrVShbmq6LtHCq4TWKjCBO/PFfUq4CWy3Z6vec/ATZNphwwDZkkNfpoO9gqgw7EgniExfky8lPmKZCvYeThbQ/X0yfX5d9mfx7/G5Ykp2G5+Zsg3g4QelSa6k701EyFIC8YaADKmay9l3+I/zLGYNiOYj1Ty8hDgKzgB5do/zOSzH1bQ80IaeA8bUaIEhT610fcqixlgofFBKxl6Cjt/hQy8MEUdXH3gDns+cy+sOk0rB8ks5UGDKM+6RrOsaMJCAk2Z9M5h6FAnJ1Vg4j9VqUu7/CX6WfaBjICjVRc7oIiAvwguiXl3s+1OT+miDVJzQXVwc/sspdAkBEpOo4RX3DNtWTq+gqOvgG7TxzHpD6tjXlr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-token
      namespace: flux-system

