apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-token
  namespace: flux-system
spec:
  encryptedData:
    address: AgCU19VhOXZD60Ne5MMGh2tn6woDqq77Nag3aJc//ABhSepwnrt9GWqgSVkNuMnsAYhoi12OWMGMup1cUE00vuOWjs6VkIAPvqRvaVSOdhVZJDLEYfSsd1dNi3/5PAEl32Xyx+5aIe5c81wsoTvY8Dkl5Tli0Z5yIJYH1qfYRmlQbCaMfeor3LH3uO17MM9MS5fTBXcAQ6K3IQ7+JzheUjGp913nXMBVWIltxLvVdS0Y5ppX1UG4QFjC3y30oA/dz5f6Fb20C2QXUrcr9ZKbqATiY+fqeUTs4x6f3XBBQKaza2YDaayhymM6Re31KJydbT9X/Jaq08xIMyQcZwo3f9A19h3IT31FS3anBdOtFr/+4x5K53My6nhwj+zaG/6HsK/Xjrq7v1yXEnp3M5gHREB1L2Y/S3s9lMINwA9Y5LJIxyIVewbIObexrBh5sQlN/rHavMX1NsULG80z2kWKxDxmFi7x/Fdt+S40c8ejBJssFCAFDO10nr8PJWxJRdqGb/Fo0wxM2sxxIwpKtantRc5+XMqae6YM8qGOxCf8nb+JyQbyUaYz0Yd1BiKtkS1jGMbH0zisBigUO+P54Bd3u/AUVUhvDWmx/lzL7xiUjx6c+RBEm7lEAaKBm5tPOUlR0dL627khPn31GKkjQRdI0y9Gf1Petfg7v0V7opMNR+Un/ygaypgvJDpsRoCa4r78TvcIadyglxr9iO+cY5koIcq9k+iA5IEvGj+R
    token: AgAXRO4uY9RMKVPj7jFHjbBUaEyRkXa14LLN1v9K76tJ0L/8aex3xddCEFU3fXdFDsoukPbbSz32XYGVKMY6P088TB14Aifp8Mqkg9xHMRpH2ZSBCshLnvWTr5vbbwWtR9ghlYL1Dj8X6DuMsp8n6N5sDhtGQgHkVYtt0V75Ydurw4KtgxLjvb/cPNFnuJDMfwpGshMuI/1tWK/vwCC3DAUyV8n6kCIj+8xzfkBkKZ2ayRiN7qLHKScgYtnSns+KEJA6+3lbvVl60Q5yj4dJ9m4XTatb3zLErKg/Qs8OTFqcbBkNKRYNE9Jm22zdX0O217t9xxXitpKnfohqAy9NnPO9OJNsrrI3ogJGZ8GjYo9nczhZXOWf+ULUvPJMZy6Fr9pmdQU0Zy6xVyQoHZeTPHN1j1NV3vS8zbJi6o3c8tj1U92wOerfgimS/W3GEquW78P42rh5iRtrl9TMVOvpVwiX0UIukAg6pczbjsk6zsUX373uNCnWm1z9xkesOGXQelUDLTm3aKgR4UUlYeZwW5bYfvqW4L2+YddRgSVrmGh66KqAXBlzjXGla4SbSZLsfhFqNOxAMEFKBbtpJUQLlgCYwOtR36o1Mm2MvSNjkFMBRG0pneQursEH/UCIUcgfeWpa6ciFN/mK4Nml+2ufYFekCCSXRPSessBGSdsz1eKAHSA1OmbXUs9PzGq1kWzzamUSWqsOCNbgaWx5BgVXLQriTJd3PBGro8nOWdjol4oGBgWYIGeSflO0ogqP5uN8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: telegram-token
      namespace: flux-system

