apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAY2jwVoAj9cvz0YgE7reoU2zjhhk+DtKUYp2WYwBO+THCQYk2nZXxzRtVGH4JgllDxHhhn2pAnJ0U3Bx0f+rO+iJgrYuWqAGwVDCkM+7NsF+h44vz2vd18irQt+Q67IWnPbeE2e6DJY4TPt6gu5OlwASyBYoBzpArzKAxsFSMXgvj2eIQNDghuHM8peeRaMV5nRomOyytN4bht81kEe+DJ5v14DMRfhAwbp/dpcWKy+POtMphgdhBbqeTPdgY3E0j/ljl8LPnhVbDnYkPO2aX5GmfK0Mq77qUlOd8puzBUGrYlSmIhs7uCjNQxsXB2vrbY2zOy8MfQF8NRxtedRhkCGLeOPdXoGOH66r+AUcw68T/hRbgW8sbMLThl/HGCEA2De5n222vp4vh/ngP9H7N7rU8PXTtWdR+9FfbTj9z/fVcbY8FjlbBWMOsbyfWdbjvJ+9iRZA3us6rirA94S5z07JeZPxvewALrQB4iXkcHib6dCIiQMW38iBuW1yFtPe7LpMQ8gaMtcT0nfJQhENYyBoCEs7KOVevA3y7/IihycG9lFHrpxhYhQ/HXdA/YTi73MtN4w/q0TvBje21dOUPi9CSf4D6QIkADfm5vwhwIs8qVo9ezWC/0GMggn61JBunpJ+hAerlFNWH7AabNVlIN+epLAUa5to+iQJNWjppe7EqG1AAwM1sgxIGleQnXaS0dDz6egV/LC80wMPKkte7uBEy8bGpkWXIHVroKhoVKwZ6oYgzdV82d
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system

