apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workadventure
  namespace: workadventure
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: workadventure
  path: ./workadventure
  prune: true
  wait: true
  timeout: 5m0s
