---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: workadventure
  namespace: workadventure
spec:
  interval: 5m0s
  url: https://github.com/MartiniMoe/workadventure-k8s.git
  ref:
    branch: main
