apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-server
  namespace: minecraft-server
spec:
  releaseName: minecraft-server
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
