apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - ../base/echo-server
  - ../base/minecraft-server
  - ../base/grafana
  - ../base/skooner
  - ../base/workadventure
  - skooner-ingress.yaml
  - workadventure-release.yaml
patchesStrategicMerge:
#  - echo-server-values.yaml
  - minecraft-server-values.yaml
