apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skooner
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - skooner.kube.martini.moe
      secretName: skooner-cert
  rules:
  - host: skooner.kube.martini.moe
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: skooner
            port:
              number: 80

